#!/usr/bin/env bash
# This script displays lines containing the word 'bash' to get the PID of the Bash process

# shellcheck disable=SC2009

# Display lines containing the word 'bash' and filter out grep command itself
ps aux | grep bash | grep -v grep

