#!/usr/bin/env bash
#A Bash script that stops 4-to_infinity_and_beyond process.

# Find the PID of the process named "4-to_infinity_and_beyond"
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$pid" ]; then
    # Send a termination signal to the process
    kill "$pid"
fi
