#!/usr/bin/env bash
# Define a function to handle SIGTERM signal
function handle_sigterm {
    echo "I am invincible!!!"
}

# Register the function to handle SIGTERM signal
trap handle_sigterm SIGTERM

# Loop indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done

