#!/usr/bin/env bash
#A Bash script that displays Best School 10 times, but at the 9th iter it displays Hi
i=0
while [ $i -lt 10 ]; do
	echo "Best School"
	if [ $i -eq 8 ]; then
		echo "Hi"
	fi
	((i++))
done
