#!/usr/bin/env bash
# A script that displays "Best School" 10 times using a while loop.

cnt=0
while [ $cnt -lt 10 ]
do
	echo "Best School"
	if [ $cnt -eq 9 ]
	then
		echo "Hi"
	echo "Best School"
	fi
	((cnt++))
done
