#!/usr/bin/env bash

cnt=0
while [ $cnt -lt 20 ]
do
	echo "$cnt"
	case $cnt in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((cnt++))
done
