#!/usr/bin/env bash
#A Bash script that configures an Ubuntu server.
cp  /etc/hosts ~/hosts_new

sed -i "s/127\.0\.0\.1/127.0.0.2/" ~/hosts_new
echo "8.8.8.8       facebook.com" >> ~/hosts_new

cp -f ~/hosts_new /etc/hosts
